version: 0.2

phases:
  pre_build:
    commands:
      - cd luca-client
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: luca-client/build
